[workspace]
members = [
    "hello",
    "without_bundler",
    "import_from_js",
    "char",
    "wasm_in_wasm",
    "hello_world_dom",
    "closures",
    "performance",
    "fetch",
    "todo_mvc",
]