[package]
name = "performance"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.80"
humantime = "2"

[dependencies.web-sys]
version = "0.3.4"
features = ["Window", "Performance", "PerformanceTiming"]
